# Generated by Django 3.1.2 on 2020-10-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201009_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
    ]
