# Generated by Django 3.1.2 on 2020-10-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_devops', models.CharField(max_length=60, verbose_name='Fullname')),
                ('key_words', models.CharField(max_length=500, verbose_name='Key words')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('faq_icon', models.ImageField(upload_to='images', verbose_name='Faq icon')),
                ('logo', models.ImageField(upload_to='images', verbose_name='Logo')),
                ('description', models.TextField(verbose_name='Description')),
                ('project_developing_start_time', models.DateField()),
                ('project_developing_finish_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CakeFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'CakeFeature',
                'verbose_name_plural': 'CakeFeatures',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60, verbose_name='Fullname')),
                ('email', models.CharField(max_length=40, verbose_name='Email')),
                ('phone_number', models.PositiveIntegerField(verbose_name='Phone Number')),
                ('location', models.CharField(max_length=100, verbose_name='Our location')),
            ],
            options={
                'verbose_name': 'Our Contact',
                'verbose_name_plural': 'Our Contacts',
            },
        ),
        migrations.CreateModel(
            name='CupCakeFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'CupCakeFeature',
                'verbose_name_plural': 'CupCakeFeatures',
            },
        ),
        migrations.CreateModel(
            name='DesertFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'DesertFeature',
                'verbose_name_plural': 'DesertFeatures',
            },
        ),
        migrations.CreateModel(
            name='EastSweetFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'EastSweetFeature',
                'verbose_name_plural': 'EastSweetFeatures',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.CreateModel(
            name='EastSweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('short_description', models.CharField(max_length=500, verbose_name='Short Description')),
                ('long_description', models.TextField(verbose_name='Long Description')),
                ('main_image', models.ImageField(upload_to='images/eastSweetImages', verbose_name='Main image')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Price')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True, verbose_name='slug')),
                ('eastSweetfeatures', models.ManyToManyField(related_name='eastSweets', to='products.EastSweetFeatures', verbose_name='EastSweet Feature')),
            ],
            options={
                'verbose_name': 'EastSweet',
                'verbose_name_plural': 'EastSweets',
            },
        ),
        migrations.CreateModel(
            name='Desert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('short_description', models.CharField(max_length=500, verbose_name='Short Description')),
                ('long_description', models.TextField(verbose_name='Long Description')),
                ('main_image', models.ImageField(upload_to='images/desertImages', verbose_name='Main image')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Price')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True, verbose_name='slug')),
                ('desert_features', models.ManyToManyField(related_name='deserts', to='products.DesertFeatures', verbose_name='Desert Feature')),
            ],
            options={
                'verbose_name': 'Desert',
                'verbose_name_plural': 'Deserts',
            },
        ),
        migrations.CreateModel(
            name='CupCake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('short_description', models.CharField(max_length=500, verbose_name='Short Description')),
                ('long_description', models.TextField(verbose_name='Long Description')),
                ('main_image', models.ImageField(upload_to='images/CupCakeImages', verbose_name='Main image')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Price')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True, verbose_name='slug')),
                ('cupCakeFeature', models.ManyToManyField(related_name='cupcakes', to='products.CupCakeFeatures', verbose_name='CupCake Feature')),
            ],
            options={
                'verbose_name': 'CupCake',
                'verbose_name_plural': 'CupCakes',
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('short_description', models.CharField(max_length=500, verbose_name='Short Description')),
                ('long_description', models.TextField(verbose_name='Long Description')),
                ('main_image', models.ImageField(upload_to='images/cakeImages', verbose_name='Main image')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Price')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True, verbose_name='slug')),
                ('cake_features', models.ManyToManyField(related_name='cakes', to='products.CakeFeatures', verbose_name='Cake Feature')),
            ],
            options={
                'verbose_name': 'Cake',
                'verbose_name_plural': 'Cakes',
            },
        ),
    ]
