# Generated by Django 3.1.2 on 2020-10-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='name_of_unit',
            field=models.CharField(default='kq', max_length=50, verbose_name='Unit name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cake',
            name='unit',
            field=models.PositiveSmallIntegerField(default='1', verbose_name='Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cupcake',
            name='name_of_unit',
            field=models.CharField(default='', max_length=50, verbose_name='Unit name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cupcake',
            name='unit',
            field=models.PositiveSmallIntegerField(default='1', verbose_name='Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desert',
            name='name_of_unit',
            field=models.CharField(default='', max_length=50, verbose_name='Unit name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desert',
            name='unit',
            field=models.PositiveSmallIntegerField(default='1', verbose_name='Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eastsweets',
            name='name_of_unit',
            field=models.CharField(default='', max_length=50, verbose_name='Unit name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eastsweets',
            name='unit',
            field=models.PositiveSmallIntegerField(default='1', verbose_name='Unit'),
            preserve_default=False,
        ),
    ]
