# Generated by Django 3.1.2 on 2020-10-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201007_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'CakeType',
                'verbose_name_plural': 'CakeTypes',
            },
        ),
        migrations.AddField(
            model_name='cake',
            name='cake_types',
            field=models.ManyToManyField(related_name='cakes', to='products.CakeTypes', verbose_name='Cake Type'),
        ),
    ]
